name: playwright tests

on:
  workflow_dispatch:
    inputs:
      browser:
        description: 'The browser to use'
        default: 'firefox'
        required: true
        type: choice
        options:
        - firefox

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.48.1-noble
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Test
        run: |
          npm install
          npx playwright test
        continue-on-error: true
        env:
          HOME: /root
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact_test
          path: playwright-report

  commit:
    needs: test
    runs-on: ubuntu-latest  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        # for commit in same repo, delete the 'with' section
        #with:
        #  repository: harmin-parra/tractive
        #  ref: 'main'
        #  token:  ${{ vars.TOKEN }}
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: artifact_test
          path: playwright-report
      - name: Commit
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "noreply@github.com"
          git rm -r docs/*
          mv playwright-report/* docs/
          git add -f docs/*
          git commit -m "Github Actions commit"
          git push origin main
